name: default

on:
  push:

jobs:
  provisioning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cat<<EOE > .env
          AWS_ACCOUNT_ID=YOUR_AWS_ACCOUNT_ID
          AWS_DEFAULT_REGION=us-east-1
          CLOUDSDK_CORE_PROJECT=YOUR_GCP_PROJECT_ID
          PROJECT_UNIQUE_ID=YOUR_GCP_PROJECT_UNIZUE_ID
          EOE
      - run: |
          echo "UID=$(id -u)" >> .env
          echo "GID=$(id -g)" >> .env
          echo "DOCKER_GID=$(getent group docker | cut -d : -f 3)" >> .env
      # - run: |
      #     echo "AWS_ACCESS_KEY_ID=${PROVISIONING_AWS_ACCESS_KEY_ID}" >> .env
      #     echo "AWS_SECRET_ACCESS_KEY=${PROVISIONING_AWS_SECRET_ACCESS_KEY}" >> .env
      #   env:
      #     PROVISIONING_AWS_ACCESS_KEY_ID: ${{ secrets.PROVISIONING_AWS_ACCESS_KEY_ID }}
      #     PROVISIONING_AWS_SECRET_ACCESS_KEY: ${{ secrets.PROVISIONING_AWS_SECRET_ACCESS_KEY }}
      #     PROVISIONING_GOOGLE_SA_KEY: ${{ secrets.PROVISIONING_GOOGLE_SA_KEY }}
      # - run: docker-compose build
      # - run: docker-compose up
      # - run: docker-compose run provisioning terraform fmt -check
      # - run: docker-compose run provisioning terraform plan
      # - run: docker-compose run provisioning terraform apply -auto-approve
      #   if: github.ref == 'refs/heads/main'
